config/routes.rb
Rails.application.routes.draw do
  resources :follows, only: [:create]
  resources :topics
  resources :answers
  resources :questions
  devise_for :users
  root 'home#index'
  get 'following' => 'home#following'
  get 'follow_topic' => 'home#follow_topic'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :followable, polymorphic: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_and_belongs_to_many :topics
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :questions
  has_many :follows, as: :followable

  validates_uniqueness_of :name

  def self.set_topic(que, user, topics)
    topics = topics.split(',')
    topics.each do |topic_name|
      topic = Topic.find_by(name: topic_name)
      if topic.blank?
        topic = Topic.create(name: topic_name, user_id: user.id)
      end
      que.topics << topic
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :answers
  has_many :topics
  has_many :follows, as: :followable

  def following
    user_ids = Follow.where(followable_type: "User", user_id: self.id).pluck(:followable_id)
    @users = User.where(id: user_ids)
  end

  def topics
    topic_ids = Follow.where(followable_type: "Topic", user_id: self.id).pluck(:followable_id)
    @topics = Topic.where(id: topic_ids)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def index
    @answers = current_user.answers.all
  end

  def show
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = current_user.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer.question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to  @answer.question, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question = @answer.question
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:name, :user_id, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  def create
    if params[:key] == "topic"
      topic = Topic.find(params[:id])
      follow_found = Follow.where(user_id: current_user.id, followable: topic).any?
      if follow_found
        flash[:notice] = 'Topic already followed'
      else
        Follow.create(user_id: current_user.id, followable: topic)
        flash[:notice] = 'Topic followed'
      end
    elsif params[:key] == "user"
      user = User.find(params[:id])
      follow_found = Follow.where(user_id: current_user.id, followable: user).any?
      if follow_found
        flash[:notice] = 'User already followed'
      else
        Follow.create(user_id: current_user.id, followable: user)
        flash[:notice] = 'User followed'
      end
    end
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @questions = Question.all
  end

  def following
    user_ids = Follow.where(followable_type: "User", user_id: current_user.id).pluck(:followable_id)
    @users = User.where(id: user_ids)
  end
  
  def follow_topic
    topic_ids = Follow.where(followable_type: "Topic", user_id: current_user.id).pluck(:followable_id)
    @topics = Topic.where(id: topic_ids)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = current_user.questions.all
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    respond_to do |format|
      if @question.save
        Topic.set_topic(@question, current_user, params[:question][:topic])
        format.html { redirect_to root_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to root_path, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:name, :user_id)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all
  end

  def show
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
<% if answer.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

    <ul>
        <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
</div>

<%= form.hidden_field :question_id %>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>User</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <% @answers.each do |answer| %>
    <tr class="answer">
        <td><%= answer.name %></td>
        <td><%= answer.user.email %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @answer.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/follows/_form.html.erb
<%= form_with(model: follow, local: true) do |form| %>
  <% if follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
        <% follow.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :followable_id %>
    <%= form.text_field :followable_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Follows</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Followable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= follow.user_id %></td>
        <td><%= follow.followable_id %></td>
        <td><%= link_to 'Show', follow %></td>
        <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
        <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New Follow</h1>

<%= render 'form', follow: @follow %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @follow.user_id %>
</p>

<p>
  <strong>Followable:</strong>
  <%= @follow.followable_id %>
</p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>

app/views/home/follow_topic.html.erb
<p id="notice"><%= notice %></p>

<h1>List of users the user follows</h1>

<table>
    <thead>
        <tr>
            <th>Email</th>
        </tr>
    </thead>

    <tbody>
        <% @topics.each do |topic| %>
        <tr>
            <td>
                <%= topic.name %>
                <%= link_to "follow topic", follows_path(id: topic.id, key: "topic" ),class: "follow_topic", method: :post %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/home/following.html.erb
<p id="notice"><%= notice %></p>

<h1>List of users the user follows</h1>

<table>
    <thead>
        <tr>
            <th>Email</th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.email %>
                <%= link_to "follow user", follows_path(id: user.id, key: "user" ),class: "follow_user", method: :post %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/home/index.html.erb
<h1>Questions</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th colspan="2">User</th>
            <th colspan="2">Topic</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @questions.each do |question| %>
        <tr>
            <td><%= link_to question.name, question %></td>
            <td>
                <%= question.user.email %>
            </td>
            <td>
                <%= link_to "follow user", follows_path(id: question.user.id, key: "user" ),class: "follow_user", method: :post %>
            </td>

            <td colspan="3">
                <% question.topics.each do |topic| %>
                <%= topic.name %>
                <%= link_to "follow topic",  follows_path(id: topic.id, key: "topic" ) ,class: "follow_topic", method: :post %></br>
                <% end %>
            </td>

            <td><%= link_to 'Edit', edit_question_path(question) %></td>
            <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>QuoraApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <h1>Quora App</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <h3>
        <div id="user_nav">
            <%= link_to "Home", root_path %> |
            <%= link_to 'Ask Question', new_question_path %> |
            <%= link_to "All Questions", root_path, class: "question" %> |
            <%= link_to "Your Questions", questions_path %> |
            <%= link_to "Your given Answers", answers_path %> |
            <%= link_to "Topics followed", follow_topic_path %> |
            <%= link_to "User's following", following_path %> |

            <% if user_signed_in? %>
            <%= current_user.email %> |
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
            <% end %>
        </div>
    </h3>
    <%= yield %>
</body>

</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
<% if question.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

    <ul>
        <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
</div>

<div class="field">
    <%= form.label "topic" %>
    <%= form.text_field :topic %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th colspan="2">User</th>
            <th colspan="2">Topic</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @questions.each do |question| %>
        <tr>
            <td><%= link_to question.name, question %></td>
            <td>
                <%= question.user.email %>
            </td>
            <td>
                <%= link_to "follow user", follows_path(id: question.user.id, key: "user" ),class: "follow_user", method: :post %>
            </td>

            <td colspan="3">
                <% question.topics.each do |topic| %>
                <%= topic.name %>
                <%= link_to "follow topic",  follows_path(id: topic.id, key: "topic" ) ,class: "follow_topic", method: :post %></br>
                <% end %>
            </td>

            <td><%= link_to 'Edit', edit_question_path(question) %></td>
            <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Name:</strong>
    <%= @question.name %>
</p>

<p>
    <strong>User:</strong>
    <%= @question.user.email %>
    <%= link_to "follow user", follows_path(id: @question.user.id, key: "user" ),class: "follow_user", method: :post %>
</p>

<td colspan="3">
    <% @question.topics.each do |topic| %>
    <%= topic.name %>
    <%= link_to "follow topic",  follows_path(id: topic.id, key: "topic" ) ,class: "follow_topic", method: :post %></br>
    <% end %>
</td>
<p>
    <strong>Answers:</strong>
</p>
<p>
    <%= link_to 'New Answer', new_answer_path(question_id: @question.id) %>

    <% if @question.answers.present? %>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>User</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <% @question.answers.each do |answer| %>
        <tr class="answer">
            <td><%= answer.name %></td>
            <td><%= answer.user.email %></td>
            <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
            <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </table>
    <% else %>
    <p class="answer">No Answers yet</p>
    <% end %>
</p>

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.user_id %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @topic.user_id %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>